### ISSUE TITLE
Daily database backup

### ISSUE THREAD

**Issue by yusuf4u52** [murtaza52/faiz-static#162]

**Comment by yusuf4u52** [comment]
Probably to drive

**Comment by yusuf4u52** [comment]
the user yusuf needs the file permission from the root in order to do the database table backup. please assign the aforementioned user the required permission. these things were discussed on whatsapp a whille ago

if it is not possible to do so, here are some alternatives
1. somehow get raw output like csv and then email or store it somewhere
2. copy the table every day with a new name, take the backup every sunday maybe
3. do it manually

**Comment by murtraja** [comment]
![faizstudents_backup](https://cloud.githubusercontent.com/assets/7806954/17339297/dcdba490-5908-11e6-845f-38fa9c36ff7a.PNG)

a very simple attempt to take backup
1. just go to the url www.faizstudents.com/backup
2. it will take some time and will provide a url of the spreadsheet (s)
3. (s) will contain sheets containing data from the tables. i.e. no. of tables = no. of sheets in (s)
4. the name of (s) is the timestamp when this backup was created
5. in order to actually access the sheet, you should log in to faizstudentsbackup@gmail.com. use the password which i will provide you

**Comment by murtraja** [comment]
the previous approach had the shortcoming that we needed a xlsx to sql converter in order to make any use of the backup file.
this approach is clumsy but does the job, an email is fired to faizstudentsbackup@gmail.com and the body of the message contains the .sql backup of the database
thanks to http://stackoverflow.com/a/31531996/4014182
@yusuf4u52 please check the /backup/_email_backup.php file and add it to cron job
for password for faizstudentsbackup@gmail.com, please contact me

**Comment by murtraja** [comment]
fixed the issues
1. now .sql file is attached with email
2. it has a date stamp on it

**Comment by yusuf4u52** [comment]
backup script will now run with the CR NR email cron job.
