### ISSUE TITLE
Draft Email - MR

### ISSUE THREAD

**Issue by mustafamnr** [murtaza52/faiz-static#85]
Draft an email for : 

**1. Successfully registered. **

We received your request. Go to faiz and complete the formalities. 

Put MR no. for 24/7/365 oncall support.

**2. Activate : **

Your thali no. is " ". 

Rule and responsibilities.

**3. Reject : **

Salam %name%,

Your thali has been not been activated as we are not currently able to deliver thali at your provided address. For any queries please mail us at help@faizstudents.com.

Aa email ma, poona ma jitna FMB che, ye logo na contact no. api sakai che. i.e Husaini Baug, Kasarwadi, City etc)

EMAIL ek dum chakachak lagwu joiye. like ITS.

**Comment by yusuf4u52** [comment]
Final Draft : 
Salaam Burhanuddin Bhai,

Mubarak for starting your Faiz ul Mawaid il Burhaniyah Thaali -

Your Thali No. will be : Thali#

1) If you need any help please email us on help@faizstudents.com or watsapp us on 9923109052, 9923, 9923. 

2) You can start / stop your thaali and update your details from the site  - www.faizstudents.com

2) Please ping +919860225717 to join the Faiz WhatsApp Group. All Faiz announcements are sent through it so please join it.

3) Subscribe to the Google mailing list - https://groups.google.com/forum/#!forum/faizstudents/join - This group can be used to send enquiries regarding vancancies, looking for roomates etc.

4) Please ensure your hub is paid before the first of every Hijri Month. Transport will not be available from first Saturday of every month if hubs are pending. If you have any problems in paying the hub please contact us in advance. 

5) Please ensure you return a washed tiffin everyday. If your tiffin is unwashed / partially washed or not returned, your thaali will not be delivered the next day. In this case you will have to pick it up from Faiz, your thaali will not be delivered that day. However the bhai doing delivery will come to take the empty tiffin, so that your thaali can be delivered the next day. He will only take one empty tiffin. 

6) If your thaali is in pickup for - unpaid hub, unreturned tiffin - and you fail to pick it up, then you will be charged Rs 200 fine for wastage of Muala's jaman.

7) Faiz time is between 9-11 AM Mon - Sat. Pickups and hub collection at Faiz will only happen in this time. 

8) If you need any help please email us on help@faizstudents.com or WhatsApp us personally.
 
Abeede Sayedna (TUS)
Faiz Khidmat Team
